import { Injectable } from "@angular/core";
import { VosaData } from "../model/vosa";

@Injectable()

export class VosaService{
    private about = new Array<VosaData>(
        { id: 1, title: "Na rai vakaitaukei me baleta na nona umani edua na tamata", details: "Na rai vakaitaukei me baleta na nona umani edua na tamata.\nKo ira na itaukei era sega ni ra dau okati ira mera cavutu mai ena dua na matanitu vaka politiki me vaka sa ra tu ena gauna edaidai. Mei vakaraitaki, ke tarogi edua na itaukei se cavu tu mai vei? Ena nona sau ni taro mai na nona yasana, tikina, koro kei na nona yavusa kevaka me gole sara vakatitobu. Ena sega ni cavuta o koya ni cavutu mai na matanitu o Viti, me vaka ga ni sega ni rogorogo donu koya. Ia, e bibi talega meda kila ni ra sega talega ni ra dau vakatakilai ira  me ra dui tamata yaduadua ga vakai ira, me vaka beka na veimata kawa – tamata tale eso. Ko ira na itaukei, era dau vakatakilai ira mera lewe ni dua na Yavusa kara semati vakaveiwekani se vaka - dra. Na yavusa era vakatakilai ira kina oqo sai koya na yavusa e cavu tu mai kina na nodra tubutubu turaga ka ra vasu kina yavusa e cavu tu mai kina na nodra itubutubu marama. E dina ni na dau cavuti ga vua edu na itaukei ena vanua e cavu tu mai kina o tamana, Ia e sega ni vakamamadataka na nona vakatakilai ena yasana vei tinana, me vaka ni dua na ka bibi vana noda ivakarau vakavanua vakaitaukei sai koya na ‘vasu’. Na vosa oqo na ‘iCavuti’ e vakaraitaka ni dua e cavu tu mai ena vanua ka a cavuti tiko me kena ivakatakilakila. Na bibi ni icavuti e qai dau matanataki ena gauna ni vakacacabo vakavanua ena veisoqo vakavanua eso", visible: true},
        { id: 3, title: "The veisau ni gauna: Mai na vakagusu kina vakaivola", details: "The veisau ni gauna: Mai na vakagusu kina vakaivola \nEna gauna taumada, o Viti esa kilai vakasigalevu tu ni sega ni dau volai vakaivola na kena itukutuku, ia e dau tukuni ga vakagusu na kena itukutuku kei na kena itovo, ka ra dau wili-gusu taki ka katoni sara vakavinaka na kena itukutuku bibi, ka oka tale tiko ga kina na icavuti. Era dau tu vei ira na kaukauwa me ra cavu qaqa taka na itukutuku  bibi vakavanua e vuqa, ka oka kina na icavuti, ka sa kani rarawa me tukuni ni sa yali sara tiko yani vakamalua na kila ka vakavanua oqo. Ena kena sa dau vakayagataki vakawasoma sara tiko na veika e volai vakaivola (iqi kina pepa), esa vakayalia sara tiko na kena dau nanumu dei ka cavuqaqa taki na veitukutuku bibi vakavanua. Na icavuti esa dua vei ira na itukutuku bibi vakavanua qoka, ka sa yali sara tiko na kena kilaka, me vaka ni vuqa sara na gauna, eda sa biuta laivi na itaukei na kena wiligusu taki na icavuti vakavanua kei na kena vei vosa bibi vakavanua e salavata mai, ka sara vakayagataka ga vakatabakidua na veika volai vakaivola. Ia, me vaka ni vakaiyalayala ga na iwiliwili ni tamata era rawa ni raica na icavuti ka sa tabaki oti tu vakaivola, esa laki vakavuna sara tiko na kena dau cavuti cala se tabonaki na kedra icavuti dina eso na veidela ni yavu vakaturaga, ka sa dau vakavuna sara na bucini ni itovo sakasaka se balea, ka dau laurai kina na veibeci, ena noda tiko vakavanua vakaveiwekani. E sega walega ni yaco ikeya na kena revurevu. E dau vakavuna talega na vakayali ni kila-ka bibi vakavanua kei na itovo ni kena vakaraitaki.", visible: true},
        { id: 4, title: "Na sasaga ni kena vorati na leqa", details: "Na sasaga ni kena vorati na leqa \nIa, ena dua na gagadre e votu mai ena kena sagai me maroroi na itukutuku bibi vakavanua me vaka na ‘icavuti vakavanua’, esa rau mai veitauriliga sara kina na Tabana ni Vosa kei na iTovo vakaviti ena Tabacakacaka iTaukei vata kei na koronivuli ni veivakarautaki na \n University of Waikato, me bucini edua na iyaragi ena monalivaliva ni vakau itukutuku ka vakatokai vakaperitania me ‘mobile web applicaition’, ka sana vakarawarawataka sara vakalevu na kena digovi se raici na vei cavuti vakaturaga ni vei delaniyavu tabu saka yani, ena kedra icavucavuti dodonu ka ra dui kilai kina. Ena rawarawa sara na kena vakayagataki ka gadrevi ga vei ira na vakayagataka ena talevoni veikauyaki mera taipa taka ga na yacani yavusa era via kila na kena icavuti vakavanua, se mera dusia ga ena mape na  koro era via kila na kedra icavuti vakavanua ni veiyavusa e tiko ena lomani koro koya. \n Na iyaragi ni sokumuni itukutuku qoka ena mona livaliva (application) vata kei na itukutuku kece e umani ena application qoka e nona vakatabakidua na Tabana ni Vosa kei na iTovo Vakaviti. Ke vaka e dua na vakatataro e tiko se dua  na vakasama e gadrevi me soli mai, e rawa ni vagolei vakatabakidua kina Tabana ni Vosa kei na iTovo vakaviti, ka rawa nio ni veitaratara kei ratou ena draunipepa ena monalivaliva qoka ka volai koto kina na ‘Contact’. Mei tinitini, na bucini ni iyaragi ni mona livaliva qoka (application) e vakailavotaka na Yunivesiti kei Waikato ka vakatokai vakaperitania me University of Waikato Summer Research Award 2019/20.", visible: true},
        { id: 5, title: "Vakavinavinaka", details: "Vakavinavinaka\nTabana ni Vosa kei iTovo Vakaviti, Tabacakacaka iTaukei \nDirector, Tabana ni Vosa kei iTovo Vakaviti – Mrs Marilyn Tagicakibau (Namuka, Nakelo, Tailevu) \niCavuti Data Coordinator/Analyst – Mr Simione Sevudredre (Naburenivalu, Namena, Tailevu)", visible: true}

    );


    getAbout(): Array<VosaData>{
        return this.about;
    }

    getAboutID(id: number): VosaData{
    return this.about.filter((detail) => detail.id === id)[0];
    }

}
